### ISSUE TITLE
include_all_day not seems to work

### ISSUE THREAD

**Issue by jflefebvre06** [franc6/ics_calendar#111]
Hello,

I try to integrate with the following config (french School vacation)

```
ics_calendar:
  calendars:
    - name: "Vacances scolaires 2"
      url: "https://fr.ftp.opendatasoft.com/openscol/fr-en-calendrier-scolaire/Zone-B.ics"
      include_all_day: True

```

![image](https://github.com/franc6/ics_calendar/assets/2685607/d7298681-ebd8-49a9-bc71-78dd991a8d52)

All day not seems to work
