### ISSUE TITLE
Failed to open url: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1006)

### ISSUE THREAD

**Issue by JabbaFire** [franc6/ics_calendar#122]
Hey,
I set up this extension with outlook.live.com (not 365). In my configuration.yaml I include the ics_canendar:

`ics_calendar: !include ics_calendar.yaml`

And in the ics_calendar.yaml I configured:

```
calendars:
    - name: Gemeinsam
      url: "https://outlook.live.com/owa/etc.ics
      include_all_day: True
      download_interval: 120
      days: 5
```
Of course for here, I have customized the URL.

In Home Assistant in the Calendar-Tab I see the Name I specified. But no content loads.

In the LOG I see an error:

`2024-01-22 19:23:45.499 ERROR (SyncWorker_54) [custom_components.ics_calendar.calendar] Gemeinsam: Failed to open url: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1006)`

Any ideas? Thanks for help.
