### ISSUE TITLE
Add units to connection_timeout option in the documentation

### ISSUE THREAD

**Issue by joluas** [franc6/ics_calendar#124]
Hello,

Today I was got the following error message in HA:
```
Updating ics_calendar calendar took longer than the scheduled update interval 0:01:00
```

After reading the documentation, I noticed that I could use `connection_timeout` option to solve this issue. However, the value is only described as a float value, but I have no idea if it is seconds, minutes or what kind of unit this field takes. I changed the configuration as follows:

```
ics_calendar:
  calendars:
    - name: "TWC"
      url: "URLRataAlada"
      include_all_day: false
      connection_timeout: 300
```

Afterwards I got the following warning from HA:
```
Update of calendar.twc is taking over 10 seconds
```
And at the end, the issue was solved. However I am not sure that I am using a proper value for the setting `connection_timeout`.

If you could let me know if the value is correct I will appreciate it and I hope that the suggestion makes sense to add it to the documentation.

Thanks for this tool
