### ISSUE TITLE
download bursts

### ISSUE THREAD

**Issue by agroszer** [franc6/ics_calendar#129]
Hi,

I have here 6 calendars defined in HA. Served by the same server, different URLs.
Looking at the calendar server logs, HA hammers on the server. Downloads the same calendar ics 2-6 times within the same second. Looks like the download count is specific to the calendar (e.g. no1 requests 3 times, no2 requests 4 times). Interval between the bursts is 15 mins (despite the configured 7-8 mins, but I'm not complaining about that).
I have a bunch of automations checking the calendars events.

Any idea how to debug this on the HA side, why the bursts get triggered?

**Comment by franc6** [comment]
Do your automations run simultaneously?  Is a single automation allowed to run multiple times, simultaneously? How do your automations check calendar events?  It seems possible that those automations are causing HA to request an update of calendar events for the same calendar from multiple automations at the same time.  There's no protection against that in my code, and I'm guessing HA doesn't protect against it, either, since automations tend to be "special".  If the answer to either of those first two questions is yes, I'll have to figure out how HA is running them simultaneously, in order to protect against calls to update data correctly (different techniques require different protections, and the sledge-hammer approach that would handle them all is a bad idea).  If you answered no to both, then the answer to the third question becomes critical. :)

Regarding the interval, it's a limitation inside HA.  As a general rule, HA will not request updates (from anything) more frequently than once every 15 minutes.  There are some exceptions to that, and they're difficult to explain or document (and I doubt I've encountered them all).  Setting a value of less than 15 minutes will allow those exceptions to trigger actual downloads of data.  For most users, that cause more harm than good.  I'm curious as to why you've set it more frequently, though.  If you are triggering automations on calendar entries, and updating those entries every 7 - 8 minutes, it seems to me that whatever is updating the entries will be automated, and there's probably a better solution for your HA automations; e.g. you can trigger an automation using the HA API.  If you're just trying to catch some last-minute calendar item to trigger an automation, well, there still might be a better solution. :)

**Comment by agroszer** [comment]
> Do your automations run simultaneously? 

I guess so, at least nothing stops them from doing so and there are plenty to query the same calendar.

Some are `time_pattern` triggered, some are calendar event triggered.

> Is a single automation allowed to run multiple times, simultaneously? 

AFAICS not, all have `mode: single`

> How do your automations check calendar events?

Besides the triggers some actions have 
```
  - service: calendar.list_events
    data:
      duration:
        hours: "{{ states('input_number.room_poweron_hours') }}"
        minutes: 0
        seconds: 0
    response_variable: agenda
    target:
      entity_id: !input calendar
```
with some sort of duration

**Comment by agroszer** [comment]
Here is an excerpt from the server access log, uninteresting parts removed.
`mbX` is the calendar name.

```
[06/Mar/2024:17:57:02 +0000] "GET mb8 HTTP/1.1" 200 1571
[06/Mar/2024:17:57:02 +0000] "GET mb8 HTTP/1.1" 200 1571
[06/Mar/2024:17:57:04 +0000] "GET mb5 HTTP/1.1" 200 1756
[06/Mar/2024:17:57:04 +0000] "GET mb5 HTTP/1.1" 200 1756
[06/Mar/2024:17:57:04 +0000] "GET mb5 HTTP/1.1" 200 1756
[06/Mar/2024:17:57:04 +0000] "GET mb5 HTTP/1.1" 200 1756
[06/Mar/2024:17:57:04 +0000] "GET mb1 HTTP/1.0" 200 1570
[06/Mar/2024:17:57:04 +0000] "GET mb1 HTTP/1.0" 200 1570
[06/Mar/2024:17:57:04 +0000] "GET mb1 HTTP/1.0" 200 1570
[06/Mar/2024:17:57:04 +0000] "GET mb1 HTTP/1.0" 200 1570
[06/Mar/2024:17:57:04 +0000] "GET mb1 HTTP/1.0" 200 1570
[06/Mar/2024:17:57:06 +0000] "GET mb6 HTTP/1.1" 200 1756
[06/Mar/2024:17:57:06 +0000] "GET mb6 HTTP/1.1" 429 0
[06/Mar/2024:17:57:06 +0000] "GET mb6 HTTP/1.1" 429 0
[06/Mar/2024:17:57:06 +0000] "GET mb6 HTTP/1.1" 429 0
[06/Mar/2024:18:05:01 +0000] "GET mb3 HTTP/1.1" 200 1570
[06/Mar/2024:18:05:01 +0000] "GET mb3 HTTP/1.1" 200 1570
[06/Mar/2024:18:05:01 +0000] "GET mb3 HTTP/1.1" 200 1570
[06/Mar/2024:18:05:02 +0000] "GET mb8 HTTP/1.1" 200 1571
[06/Mar/2024:18:05:11 +0000] "GET mb1 HTTP/1.0" 200 1570
[06/Mar/2024:18:05:12 +0000] "GET mb6 HTTP/1.1" 200 1756
[06/Mar/2024:18:06:01 +0000] "GET mb2 HTTP/1.0" 200 1942
[06/Mar/2024:18:06:01 +0000] "GET mb2 HTTP/1.0" 200 1942
[06/Mar/2024:18:06:01 +0000] "GET mb2 HTTP/1.0" 200 1942
[06/Mar/2024:18:12:01 +0000] "GET mb3 HTTP/1.1" 200 1570
[06/Mar/2024:18:12:04 +0000] "GET mb5 HTTP/1.1" 200 1756
[06/Mar/2024:18:12:04 +0000] "GET mb5 HTTP/1.1" 200 1756
[06/Mar/2024:18:12:04 +0000] "GET mb5 HTTP/1.1" 200 1756
[06/Mar/2024:18:12:04 +0000] "GET mb5 HTTP/1.1" 200 1756
[06/Mar/2024:18:15:02 +0000] "GET mb8 HTTP/1.1" 200 1571
[06/Mar/2024:18:15:02 +0000] "GET mb8 HTTP/1.1" 200 1571
[06/Mar/2024:18:15:02 +0000] "GET mb8 HTTP/1.1" 200 1571
[06/Mar/2024:18:15:02 +0000] "GET mb8 HTTP/1.1" 200 1571
[06/Mar/2024:18:18:01 +0000] "GET mb2 HTTP/1.0" 200 1942
[06/Mar/2024:18:18:01 +0000] "GET mb2 HTTP/1.0" 200 1942
[06/Mar/2024:18:18:01 +0000] "GET mb2 HTTP/1.0" 200 1942
[06/Mar/2024:18:20:01 +0000] "GET mb3 HTTP/1.1" 200 1570
[06/Mar/2024:18:20:01 +0000] "GET mb3 HTTP/1.1" 200 1570
[06/Mar/2024:18:20:01 +0000] "GET mb3 HTTP/1.1" 200 1570
[06/Mar/2024:18:21:11 +0000] "GET mb1 HTTP/1.0" 200 1570
[06/Mar/2024:18:21:12 +0000] "GET mb6 HTTP/1.1" 200 1756
[06/Mar/2024:18:24:02 +0000] "GET mb8 HTTP/1.1" 200 1571
[06/Mar/2024:18:24:02 +0000] "GET mb8 HTTP/1.1" 200 1571
[06/Mar/2024:18:27:01 +0000] "GET mb2 HTTP/1.0" 200 1942
[06/Mar/2024:18:27:01 +0000] "GET mb2 HTTP/1.0" 200 1942
[06/Mar/2024:18:27:01 +0000] "GET mb2 HTTP/1.0" 200 1942
[06/Mar/2024:18:27:01 +0000] "GET mb3 HTTP/1.1" 200 1570
[06/Mar/2024:18:27:04 +0000] "GET mb5 HTTP/1.1" 200 1756
[06/Mar/2024:18:27:04 +0000] "GET mb5 HTTP/1.1" 200 1756
[06/Mar/2024:18:27:04 +0000] "GET mb5 HTTP/1.1" 200 1756
[06/Mar/2024:18:27:04 +0000] "GET mb5 HTTP/1.1" 200 1756
[06/Mar/2024:18:33:02 +0000] "GET mb8 HTTP/1.1" 200 1571
[06/Mar/2024:18:33:02 +0000] "GET mb8 HTTP/1.1" 200 1571
[06/Mar/2024:18:35:01 +0000] "GET mb3 HTTP/1.1" 200 1570
[06/Mar/2024:18:35:01 +0000] "GET mb3 HTTP/1.1" 200 1570
[06/Mar/2024:18:35:01 +0000] "GET mb3 HTTP/1.1" 200 1570
[06/Mar/2024:18:35:11 +0000] "GET mb2 HTTP/1.0" 200 1942
[06/Mar/2024:18:37:11 +0000] "GET mb1 HTTP/1.0" 200 1570
[06/Mar/2024:18:37:12 +0000] "GET mb6 HTTP/1.1" 200 1756
[06/Mar/2024:18:42:01 +0000] "GET mb3 HTTP/1.1" 200 1570
[06/Mar/2024:18:42:02 +0000] "GET mb8 HTTP/1.1" 200 1571
[06/Mar/2024:18:42:02 +0000] "GET mb8 HTTP/1.1" 200 1571
[06/Mar/2024:18:42:04 +0000] "GET mb5 HTTP/1.1" 200 1756
[06/Mar/2024:18:42:04 +0000] "GET mb5 HTTP/1.1" 200 1756
[06/Mar/2024:18:42:04 +0000] "GET mb5 HTTP/1.1" 200 1756
[06/Mar/2024:18:42:04 +0000] "GET mb5 HTTP/1.1" 200 1756
```

Looking at the times (seconds) of the requests this sort of suggests, that some timer kicks off the requests (because the same calendar seems to trigger at the same second. The 15 min HASS limitation seem to play out most of the time.

Have the calendar defined:
```
ics_calendar:
  calendars:
    - name: "mb1"
      url: ...
      exclude: "['BLOCKED']"
      download_interval: 7
    - name: "mb2"
      url: ...
      exclude: "['BLOCKED']"
      download_interval: 8
    - name: "mb3"
      url: ...
      exclude: "['BLOCKED']"
      download_interval: 7
    - name: "mb5"
      url: ...
      exclude: "['BLOCKED']"
      download_interval: 8
    - name: "mb6"
      url: ...
      exclude: "['BLOCKED']"
      download_interval: 7
    - name: "mb8"
      url: ...
      exclude: "['BLOCKED']"
      download_interval: 8
```
