### ISSUE TITLE
remove calendar

### ISSUE THREAD

**Issue by oldneef** [franc6/ics_calendar#143]
Hello, 
I installed ics to try...I succeeded but now I would like to uninstall them.
When I delete in configuration.yaml file,

```
ics_calendar:
  calendars:
    - name: "Personnel"
      url: "https://url.to/calendar.ics"
```
 the created calendar is not deleted.
I tried deleting the folder in custom_components but I still have my calendar.personnel entity.
How to remove it? 
Best regards.
