### ISSUE TITLE
Room/Location Support for filter

### ISSUE THREAD

**Issue by JonasGhost** [franc6/ics_calendar#175]
**Home Assistant Setup**

Version: 2024.10.1

Installation Type (put an X between the square brackets for your HA):
[X] Home Assistant OS
[] Home Assistant OS
[] Home Assistant Supervised
[] Home Assistant Container
[] Home Assistant Core

Hardware platform:
[] ARM
[x] x86-64

**Improvement**
Add an option to filter for rooms, so that one external calendar can be split into multiple calendars inside home assistant.
One for each home-assistant managed room. The goal is, to run automation to prepare the room for the event.
e.g. change heating settings, change to door sign etc.

Currently I am using a room tag inside the description to solve that issue.

**Comment by jschutte27** [comment]
It looks like the location field is missing in the Home assistant calendar view, but if you call get events or use it in an automation the location attribute appears to be populated:

```
calendar.rentals:
  events:
    - start: "2024-12-28T17:30:00-06:00"
      end: "2024-12-28T22:00:00-06:00"
      summary: Test event
      description: No Description
      location: "Main Room"
```

I am working on a similar setup to manage rooms.
