### ISSUE TITLE
Calendar Events not being recognised by automations

### ISSUE THREAD

**Issue by Blumlaut** [franc6/ics_calendar#225]
Hi! I added my work shifts to Home Assistant using ICS-Calendar, this seems to work fine for the most part, my "Calendar" Tab is showing my shifts correctly, however, i also have an automation set up which should trigger some things 45 minutes before i leave, this automation never triggers (no traces, nothing.), as if the event simply does not exist, here is my automation:
```
alias: blumlaut work notification
description: ""
triggers:
  - trigger: calendar
    entity_id: calendar.blumlaut_work
    event: start
    offset: "-0:45:0"
conditions: []
actions:
  - metadata: {}
    data:
      message: Work in 45min!
      target: 99999999
    action: telegram_bot.send_message
mode: single
```

I have tried deleting and re-creating the calendar under a different name, however this didn't have any effect, no errors related to my automation or ics-calendar in the logs that i could find.

Of note is that i'm using the waste collection schedule integration also, which is working perfectly fine with a similar style of notification, only the calendar added using ics_calendar is not working.

System Information:
- Fully up to date HA using HAOS
- KVM VM on a 64 bit CPU
- 4GB RAM

Any help would be appreciated!

**Comment by cvwillegen** [comment]
I'm using this integration to read the school schedule for our resident student, so that I can automate things like "holidays" or other days of from school. 

Last school year, triggering on these types of events worked. This year, I had to set up a new calendar, and the configuration changed from the yaml to a flow based setup. I put in the URL of the new calendar, and I can see the events in the "Calendar" tab, but events are never triggered.

My automation looks like this: 
```
alias: No lessons
description: ""
mode: queued
triggers:
  - event: start
    entity_id: calendar.school
    offset: "-3:55:0"
    trigger: calendar
conditions:
  - condition: template
    value_template: >-
      {% if (trigger.calendar_event.summary != None and
      trigger.calendar_event.summary is
      search("(?i)"~states("input_text.filter_no_school"))) %}true{%endif%}
actions:
  - data: {}
    target:
      entity_id: input_boolean.holiday
    action: input_boolean.turn_on
```
