### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by balajeek** [franc6/ics_calendar#45]
Just trying to setup calendar on my HA (latest)
installed ics_calendar latest from hacs.

and added the config like this:
```
calendar:
  - platform: ics_calendar
    calendars:
      - name: "Recycle"
        url: "https://cal.recyclecoach.com/admin/calendars/606-EDI-collection-1497-S12097.ics"
```

The calendar "recycle" shows in the calendar tab, but no entries in there

upon checking the log file i see this error:
2022-02-27 20:38:15 ERROR (MainThread) [custom_components.ics_calendar.calendar] Recycle: Failed to parse ICS!

all this calendar contains are my recycle days, nothing big.
wondering what the problem is.
