### ISSUE TITLE
local file support?

### ISSUE THREAD

**Issue by zstonez** [franc6/ics_calendar#65]
Hi
ist there somehow the possibility to add a local ics-file to your calendar? found it .. my fault just use
url: "http://localhost:8123/local/ics_calender_file.ics"

**Comment by derbmann** [comment]
Hi,
I also need to access a local file but i can't get it to work...

I did put the File into /opt/homeassistant/config/calendar.ics
docker-compose volume mount: /opt/homeassistant/config:/config
And the configuration looks like this.:
```
calendar:
- platform: ics_calendar
  calendars:
      - name: "LocalCalendar"
        url: "http://localhost:8123/config/calendar.ics"
        download_interval: 15
        parser: "rie"
        include_all_day: True
```

If I use the same .ics as a download then the Calendar works fine.

What did you do different then I :D?
