### ISSUE TITLE
Error parsing ICS calendar from NSW Government

### ISSUE THREAD

**Issue by calvinbui** [franc6/ics_calendar#75]
HA: 2022.12.1
ics_calendar: 3.1.5

I'm looking to import public holidays supplied by the Australian NSW Government: https://www.industrialrelations.nsw.gov.au/public-holidays/public-holidays-in-nsw/#icalendar-downloads

This is my config. The user-agent is required.

```
- platform: ics_calendar
  calendars:
    - name: NSW Public Holidays 2021-2023
      url: https://staticontent.dpc.nsw.gov.au/ir/calendar/NSW-Public-Holidays-dates-2021-2023.ics
      user_agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36
```

I'm getting an error with both the `rie` and `ics` parsers. Logs attached.

A brief skim of the logs appears the issue is either to do with `BEGIN:VCALENDAR` at the top of the ICS file.

[ics.txt](https://github.com/franc6/ics_calendar/files/10203222/ics.txt)
[rie.txt](https://github.com/franc6/ics_calendar/files/10203223/rie.txt)
