### ISSUE TITLE
All-day events not recognized correctly

### ISSUE THREAD

**Issue by schwimmbadpirat** [franc6/ics_calendar#92]
I have issues with all-day events in an external ics, which are not recognized as such and instead are all entered as normal events with a timeslot 00:00 - 00:00.
Since the ics is provided by an external service, I have no control over formatting or content.
In #66 there were already similar discussions and also the hints regarding RFC and DTSTART as well as DTEND values.

HA Calendar config:
```yaml
calendar:
  - platform: ics_calendar
    calendars:
      - name: "Abfall"
        url: "https://rhein-pfalz-kreis.abfall-app.net/download?system=ical&period=1&district=728&categories=&view=year"
        include_all_day: true
        download_interval: 1440
```

The ics unfortunately only gives `DTSTART `for the events and `DTEND `is missing completely.
Additionally `X-MICROSOFT-CDO-ALLDAYEVENT:TRUE` is set, but this is probably not taken into account during parsing.
If the ics is used in other products (non HA), they are displayed as all-day events - I assume that `X-MICROSOFT-CDO-ALLDAYEVENT` is additionally evaluated there.

Event example:
```batch
UID:646343bb0d294
DTSTART;VALUE=DATE:20221231
SEQUENCE:0
TRANSP:OPAQUE
SUMMARY:Altpapier
CLASS:PUBLIC
X-MICROSOFT-CDO-ALLDAYEVENT:TRUE
DTSTAMP:20230516T085003Z
END:VEVENT
BEGIN:VEVENT
```
